/**********************************************************************
 * Extern for hdom
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var hdom = {
  "DEBUG": {},
  "clearDOM": function () {},
  "cloneWithNewAttribs": function () {},
  "createDOM": function () {},
  "createElement": function () {},
  "createTextElement": function () {},
  "diffElement": function () {},
  "hydrateDOM": function () {},
  "normalizeElement": function () {},
  "normalizeTree": function () {},
  "removeAttribs": function () {},
  "removeChild": function () {},
  "setAttrib": function () {},
  "setAttribs": function () {},
  "setStyle": function () {},
  "start": function () {},
  "updateValueAttrib": function () {}
};
/**********************************************************************
 * End Generated Extern for hdom
/**********************************************************************/